directories:
  output: dist_electron
  buildResources: build
appId: com.imai.app
productName: IM AI
files:
  - filter:
      - dist/**/*
      - electron/**/*
win:
  target:
    - target: nsis
      arch:
        - x64
  icon: public/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: IM AI
electronVersion: 35.0.1
